# Site settings
title: Bejay's Website
email: bejay.ketan1@gmail.com
description: >-
  Welcome to my little corner of the internet. Full-time engineer passionate about
  GenAI, building magical experiences with clarity and logic.
baseurl: ""
url: "https://bkg123.github.io"
twitter_username:
github_username: BKG123
linkedin_username: bejay-ketan-guin-67970018a

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/